# Generated by Django 4.1.13 on 2024-01-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='videoId',
            field=models.AutoField(db_column='_id', primary_key=True, serialize=False),
        ),
    ]
