# Generated by Django 4.1.13 on 2024-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_card_videoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='videoId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
